name: test
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW: github.workflow
    steps:
      - run: echo "${{GITHUB_WORKFLOW}}"  
