name: concurrency
on: push

env: 
  GTIHUB_WORKFLOW_TEST: tom

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ GTIHUB_WORKFLOW_TEST }}"  
      
