name: test
on: push

env:
  GITHUB_WORKFLOW: ${{github.workflow}}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{GITHUB_WORKFLOW}}"  
