name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}     # 「ell」を含むか
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # 「He」で始まるか
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}     # 「lo」で終わるか
          CONTAINS_FALSE_FUNC: ${{ contains('Hello', 'ele') }}     # 「ele」を含むか
          STARTS_WITH_FALSE_FUNC: ${{ startsWith('Hello', 'Hee') }} # 「Hee」で始まるか
          ENDS_WITH_FALSE_FUNC: ${{ endsWith('Hello', 'loe') }}     # 「loe」で終わるか